version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:23.0.0
    container_name: keycloak
    command: start-dev --http-relative-path /auth
    environment:
      KC_DB: dev-file
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_PROXY: edge
      KC_HOSTNAME_URL: https://auth.dev.org/auth
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak_data:/opt/keycloak/data/
      - ./keycloak_themes/mytheme:/opt/keycloak/themes/mytheme
    extra_hosts:
      - "auth.dev.org:192.168.1.10"
      - "www.dev.org:192.168.1.10"

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:latest
    container_name: oauth2-proxy
    command: --config /oauth2-proxy.cfg
    volumes:
      - ./oauth2-proxy.cfg:/oauth2-proxy.cfg
    ports:
      - "4180:4180"
    depends_on:
      - keycloak
    extra_hosts:
      - "auth.dev.org:172.17.0.1"
      - "www.dev.org:172.17.0.1"
